### ISSUE TITLE
add peer function clause not matching

### ISSUE THREAD

**Issue by thepiwo** [aeternity/elixir-node#462]
```
iex(1)> Peers.add_peer("127.0.0.1:4000")
** (exit) exited in: GenServer.call(Aecore.Peers.Worker, {:add_peer, "127.0.0.1:4000"}, 5000)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Aecore.Peers.Worker.handle_call/3
            (aecore) lib/aecore/peers/worker.ex:94: Aecore.Peers.Worker.handle_call({:add_peer, "127.0.0.1:4000"}, {#PID<0.540.0>, #Reference<0.610387156.1598029825.134765>}, %{local_peer: %{privkey: <<40, 4, 36, 30, 97, 118, 175, 8, 235, 112, 41, 98, 82, 128, 185, 85, 126, 123, 72, 38, 168, 57, 66, 156, 206, 169, 141, 95, 244, 192, 237, 123>>, pubkey: <<69, 157, 212, 91, 37, 172, 57, 248, 125, 41, 238, 27, 197, 87, 26, 107, 90, 36, 104, 48, 68, 118, 202, 178, 16, 60, 101, 5, 142, 233, 171, 70>>}, peers: %{}})
            (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:836: GenServer.call/3
iex(1)> [error] GenServer Aecore.Peers.Worker terminating
** (FunctionClauseError) no function clause matching in Aecore.Peers.Worker.handle_call/3
    (aecore) lib/aecore/peers/worker.ex:94: Aecore.Peers.Worker.handle_call({:add_peer, "127.0.0.1:4000"}, {#PID<0.540.0>, #Reference<0.610387156.1598029825.134765>}, %{local_peer: %{privkey: <<40, 4, 36, 30, 97, 118, 175, 8, 235, 112, 41, 98, 82, 128, 185, 85, 126, 123, 72, 38, 168, 57, 66, 156, 206, 169, 141, 95, 244, 192, 237, 123>>, pubkey: <<69, 157, 212, 91, 37, 172, 57, 248, 125, 41, 238, 27, 197, 87, 26, 107, 90, 36, 104, 48, 68, 118, 202, 178, 16, 60, 101, 5, 142, 233, 171, 70>>}, peers: %{}})
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.540.0>): {:add_peer, "127.0.0.1:4000"}
State: %{local_peer: %{privkey: <<40, 4, 36, 30, 97, 118, 175, 8, 235, 112, 41, 98, 82, 128, 185, 85, 126, 123, 72, 38, 168, 57, 66, 156, 206, 169, 141, 95, 244, 192, 237, 123>>, pubkey: <<69, 157, 212, 91, 37, 172, 57, 248, 125, 41, 238, 27, 197, 87, 26, 107, 90, 36, 104, 48, 68, 118, 202, 178, 16, 60, 101, 5, 142, 233, 171, 70>>}, peers: %{}}
Client #PID<0.540.0> is alive
    (stdlib) gen.erl:169: :gen.do_call/4
    (elixir) lib/gen_server.ex:833: GenServer.call/3
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) src/elixir.erl:233: :elixir.eval_forms/4
    (iex) lib/iex/evaluator.ex:250: IEx.Evaluator.handle_eval/5
    (iex) lib/iex/evaluator.ex:230: IEx.Evaluator.do_eval/3
    (iex) lib/iex/evaluator.ex:208: IEx.Evaluator.eval/3
    (iex) lib/iex/evaluator.ex:94: IEx.Evaluator.loop/1
    (iex) lib/iex/evaluator.ex:24: IEx.Evaluator.init/4
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by d-velev** [comment]
Add peer is the function that is called whenever a connection is made (add peer to state after handshaking and pinging is done), this isn't supposed to be used when adding someone manually (use get_info_try_connect).

**Comment by thepiwo** [comment]
you are right, I confused these functions
