### ISSUE TITLE
Bug when trying to send new tx to the synced node

### ISSUE THREAD

**Issue by 0legIv** [aeternity/elixir-node#560]
How to reproduce:
1. Run two nodes: `make iex-1`, `make iex-2`
2. Sync them
3. Add a new tx to the pool in one of the nodes, for example spend_tx:
```
{pubkey, _} = Keys.keypair :sign
{:ok, tx} = Account.spend(pubkey, 20, 10, <<"payload">>)
Pool.add_transaction(tx)
```

Error:
```
[error] GenServer Aecore.Peers.Jobs terminating
** (UndefinedFunctionError) function Aecore.Peers.PeerConnection.send_new_tx/2 is undefined or private. Did you mean one of:

      * send_new_block/2

    (aecore) Aecore.Peers.PeerConnection.send_new_tx(%Aecore.Tx.SignedTx{data: %Aecore.Tx.DataTx{fee: 10, nonce: 1, payload: %Aecore.Account.Tx.SpendTx{amount: 20, payload: "payload", receiver: %Aecore.Chain.Identifier{type: :account, value: <<131, 38, 207, 89, 116, 83, 32, 200, 7, 116, 133, 153, 178, 250, 54, 237, 148, 103, 50, 110, 16, 15, 131, 194, 232, 119, 169, 120, 55, 221, 106, 81>>}, version: 1}, senders: [%Aecore.Chain.Identifier{type: :account, value: <<131, 38, 207, 89, 116, 83, 32, 200, 7, 116, 133, 153, 178, 250, 54, 237, 148, 103, 50, 110, 16, 15, 131, 194, 232, 119, 169, 120, 55, 221, 106, 81>>}], ttl: 0, type: Aecore.Account.Tx.SpendTx}, signatures: [<<193, 42, 204, 148, 167, 107, 166, 162, 186, 59, 102, 23, 157, 147, 139, 124, 194, 166, 22, 71, 73, 100, 1, 14, 61, 207, 84, 21, 228, 140, 119, 213, 42, 2, 119, 54, 194, 208, 117, 254, 69, 215, 97, 239, 252, 61, 183, ...>>]}, #PID<0.559.0>)
    (aecore) lib/aecore/peers/sync.ex:485: Aecore.Peers.Sync.process_jobs/1
    (aecore) lib/aecore/peers/jobs.ex:81: Aecore.Peers.Jobs.handle_cast/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:dequeue, :sync_jobs}}
State: %{queues: [sync_jobs: 1]}
```

**Comment by thepiwo** [comment]
@0legIv great that the multinode test framework found this issue!

**Comment by gspasov** [comment]
This is probably due to changes in the PeerConnection module required by the new Sync, which is not ready yet. Possibly after the new sync implementation is ready, this won't be an issue any more.

**Comment by thepiwo** [comment]
@0legIv @gspasov I assigned this to the milestone
